name: Duplicate Issue Bot

on:
  issues:
    types: [opened]
    
permissions:
  issues: write

jobs:
  check-duplicate:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue content for duplicates
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const content = (issue.title + " " + issue.body).toLowerCase();

            // Keywords to check
            const keywords = ["windows defender", "virus"];

            // Fixed duplicate issues list
            const duplicateMessage = `This is potentially a duplicate of #742, #741, #735, #725, #691, #665, #664, #654, #641, #634, #620, #616, #517, #508, #503, #420, #384, #335, #333, #315, #284, #270, #249, #217, #209, #137 and #13. Please review one of the existing issues and close the issue if it is addressed in one of the duplicates.`;

            let matched = false;
            for (const kw of keywords) {
              if (content.includes(kw)) {
                matched = true;
                break;
              }
            }

            if (matched) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: duplicateMessage
              });
            }
